openapi: 3.1.0
info:
  title: OAS
  description: Exercice3 OAS
  version: 1.0.0
servers:
  - url: 'https://localhost:8000'
paths:
  /tasks:
    get:
      summary: Récupère une liste des taches
      responses:
        '200':
          description: Liste des taches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Ajoute une nouvelle tache
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Liste de tache crée
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    delete:
      summary: Supprime les taches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                example: 1
      responses:
        '200':
          description: Liste des taches supprimer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
  /tasks/{id}:
    get:
      summary: Récupère les taches avec son id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tache trouver
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Tache non trouver
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Tache non trouver
    delete:
      summary: Supprime une tache par son id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tache supprimer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: laver la vaisselle
        completed:
          type: boolean
          example: false

  
